'use client';
import { useEffect, useState } from 'react';
import DashboardClient from './DashboardClient';
function currentMonth(){return new Date().toISOString().slice(0,7)}
function today(){return new Date().toISOString().slice(0,10)}
function money(n:any){return Number(n||0).toFixed(0)}
export default function AdminClient(){
 const [data,setData]=useState<any>(null); const [month,setMonth]=useState(currentMonth()); const [err,setErr]=useState('');
 const [settings,setSettings]=useState({lunchLockStart:'10:00',lunchLockEnd:'13:00',dinnerLockStart:'18:00',dinnerLockEnd:'21:00',maxMealCount:'20'});
 const [bills,setBills]=useState({seatRent:0,utilityBill:0,wifiBill:0,cookBill:0,electricityBill:0});
 const [cook,setCook]=useState({date:today(),mealType:'lunch',reason:'Cook did not come',confirmText:''});
 async function load(m=month){const r=await fetch(`/api/dashboard?month=${m}`,{cache:'no-store'});const j=await r.json(); if(!r.ok){if(j.error==='Unauthorized'){location.href='/login';return} setErr(j.error);return} setErr(''); setData(j); if(j.settings)setSettings({lunchLockStart:j.settings.lunchLockStart||'10:00',lunchLockEnd:j.settings.lunchLockEnd||'13:00',dinnerLockStart:j.settings.dinnerLockStart||'18:00',dinnerLockEnd:j.settings.dinnerLockEnd||'21:00',maxMealCount:j.settings.maxMealCount||'20'}); if(j.bills)setBills({seatRent:+j.bills.seatRent||0,utilityBill:+j.bills.utilityBill||0,wifiBill:+j.bills.wifiBill||0,cookBill:+j.bills.cookBill||0,electricityBill:+j.bills.electricityBill||0});}
 useEffect(()=>{load(month)},[month]);
 async function bazar(id:string,status:string){const r=await fetch('/api/admin/bazar',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})}); const j=await r.json(); if(!r.ok) alert(j.error); load()}
 async function saveSettings(){const r=await fetch('/api/admin/settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(settings)}); const j=await r.json(); alert(r.ok?'Settings saved':j.error); load()}
 async function saveBills(){const r=await fetch('/api/admin/bills',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...bills,month})}); const j=await r.json(); alert(r.ok?'Bills saved':j.error); load()}
 async function updateUser(phone:string, patch:any){const r=await fetch('/api/admin/users',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone,...patch})}); const j=await r.json(); if(!r.ok) alert(j.error); load()}
 async function deleteUser(phone:string){if(!confirm('Delete this user? Login will be disabled but old meal/bazar history will remain.'))return; const r=await fetch('/api/admin/users',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone})}); const j=await r.json(); if(!r.ok) alert(j.error); load()}
 async function cookOff(action='activate'){const phrase=action==='undo' ? (cook.mealType==='lunch'?'UNDO LUNCH COOK OFF':'UNDO DINNER COOK OFF') : (cook.mealType==='lunch'?'NO LUNCH COOKED':'NO DINNER COOKED'); if(cook.confirmText!==phrase){alert(`Type exactly: ${phrase}`);return;} const r=await fetch('/api/admin/cook-off',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...cook,action})}); const j=await r.json(); alert(r.ok?j.message:j.error); setCook({...cook,confirmText:''}); load()}
 if(err)return <main className="page"><div className="card errorBox">{err}</div></main>;
 if(!data)return <main className="page"><div className="card shimmer">Loading admin...</div></main>;
 if(data.user?.role!=='admin')return <DashboardClient/>;
 const required=cook.mealType==='lunch'?'NO LUNCH COOKED':'NO DINNER COOKED'; const undoRequired=cook.mealType==='lunch'?'UNDO LUNCH COOK OFF':'UNDO DINNER COOK OFF';
 return <main className="page"><div className="top hero"><div><div className="brand small">MESS<span>CORE</span></div><h1>Admin Command Center</h1><p className="muted">Users, bills, scans, cook-off interrupt and bazar verification.</p></div><div className="nav"><a className="btn2" href="/dashboard">Dashboard</a><button className="btn2" onClick={()=>load(month)}>Refresh</button><button className="btn2" onClick={()=>fetch('/api/auth/logout',{method:'POST'}).then(()=>location.href='/login')}>Logout</button></div></div>
 <section className="card glow"><label>Admin month/year</label><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/><p className="muted">Monthly calculation reads MealCounted only. Live MealStatus remains untouched by computation and cook-off.</p></section>
 <section className="grid grid2"><div className="card grid"><h2>Meal Lock Window</h2><label>Lunch Lock Start</label><input type="time" value={settings.lunchLockStart} onChange={e=>setSettings({...settings,lunchLockStart:e.target.value})}/><label>Lunch Lock End</label><input type="time" value={settings.lunchLockEnd} onChange={e=>setSettings({...settings,lunchLockEnd:e.target.value})}/><label>Dinner Lock Start</label><input type="time" value={settings.dinnerLockStart} onChange={e=>setSettings({...settings,dinnerLockStart:e.target.value})}/><label>Dinner Lock End</label><input type="time" value={settings.dinnerLockEnd} onChange={e=>setSettings({...settings,dinnerLockEnd:e.target.value})}/><label>Max meal count per meal</label><input type="number" value={settings.maxMealCount} onChange={e=>setSettings({...settings,maxMealCount:e.target.value})}/><button className="btn" onClick={saveSettings}>Save Lock Window</button></div>
 <div className="card grid"><h2>Monthly Bills ({month})</h2>{Object.keys(bills).map(k=><div key={k}><label>{k}</label><input type="number" value={(bills as any)[k]} onChange={e=>setBills({...bills,[k]:Number(e.target.value)})}/></div>)}<button className="btn" onClick={saveBills}>Save Bills</button></div></section>
 <section className="card dangerZone"><h2>Emergency Cook-Off Interrupt</h2><p className="muted">This affects MealCounted/monthly calculation only. It never changes My Current Meal Plan or Real-time Meal Status.</p><div className="grid grid2"><div><label>Date</label><input type="date" value={cook.date} onChange={e=>setCook({...cook,date:e.target.value})}/></div><div><label>Meal Type</label><select value={cook.mealType} onChange={e=>setCook({...cook,mealType:e.target.value})}><option value="lunch">Lunch</option><option value="dinner">Dinner</option></select></div><div><label>Reason</label><input value={cook.reason} onChange={e=>setCook({...cook,reason:e.target.value})}/></div><div><label>Confirmation Text</label><input value={cook.confirmText} onChange={e=>setCook({...cook,confirmText:e.target.value})} placeholder={required}/></div></div><p className="warning">To activate, type: <b>{required}</b>. To undo, type: <b>{undoRequired}</b>.</p><div className="nav"><button className="btn dangerBtn" onClick={()=>cookOff('activate')}>Mark No Cook / Force Count Zero</button><button className="btn2" onClick={()=>cookOff('undo')}>Undo Cook-Off</button></div><h3>Cook-Off History</h3><div className="tableScroll"><table><thead><tr><th>Date</th><th>Meal</th><th>Active</th><th>Reason</th><th>Created By</th><th>Undone By</th></tr></thead><tbody>{(data.cookOffs||[]).map((c:any)=><tr key={c.id}><td>{c.date}</td><td>{c.mealType}</td><td><span className={`pill ${String(c.isActive)==='1'?'approved':'rejected'}`}>{String(c.isActive)==='1'?'ACTIVE':'inactive'}</span></td><td>{c.reason}</td><td>{c.createdBy}</td><td>{c.undoneBy}</td></tr>)}</tbody></table></div></section>
 <section className="card"><h2>User Management</h2><div className="tableScroll"><table><thead><tr><th>Name</th><th>Phone</th><th>Role</th><th>Auth</th><th>Action</th></tr></thead><tbody>{(data.users||[]).map((u:any)=><tr key={u.phone}><td>{u.name}</td><td>{u.phone}</td><td><select value={u.role||'user'} onChange={e=>updateUser(u.phone,{role:e.target.value})}><option value="user">user</option><option value="admin">admin</option></select></td><td><select value={String(u.authStatus||'0')} onChange={e=>updateUser(u.phone,{authStatus:e.target.value})}><option value="0">unauthorized</option><option value="1">authorized</option></select></td><td><button className="btn2 danger" onClick={()=>deleteUser(u.phone)}>Delete</button></td></tr>)}</tbody></table></div></section>
 <section className="card"><h2>Bazar Verification ({month})</h2><p className="muted">Newest requests appear first.</p><div className="tableScroll"><table><thead><tr><th>Date</th><th>Name</th><th>Amount</th><th>Note</th><th>Status</th><th>Submitted</th><th>Action</th></tr></thead><tbody>{(data.bazars||[]).map((b:any)=><tr key={b.id}><td>{b.date}</td><td>{b.name}</td><td>৳ {money(b.amount)}</td><td>{b.note}</td><td><span className={`pill ${b.status}`}>{b.status}</span></td><td>{b.submittedAt}</td><td>{b.status==='pending'&&<><button className="btn2" onClick={()=>bazar(b.id,'approved')}>Approve</button> <button className="btn2 danger" onClick={()=>bazar(b.id,'rejected')}>Reject</button></>}</td></tr>)}</tbody></table></div></section>
 </main>
}
